_: {
  flake.nixosModules.zfs =
    {
      config,
      ...
    }:
    {
      fileSystems."/persist".neededForBoot = true;

      # ZFS needs a stable, unique-enough hostId to refuse importing a pool
      # that wasn't cleanly exported (guards against two hosts touching the
      # same disk). Deriving it from the hostname keeps it reproducible from
      # the flake instead of a one-off value generated by hand at install time.
      networking.hostId = builtins.substring 0 8 (builtins.hashString "md5" config.networking.hostName);

      boot = {
        supportedFilesystems = [ "zfs" ];

        zfs = {
          devNodes = "/dev/disk/by-id/";
          forceImportAll = false;
          forceImportRoot = true;
          requestEncryptionCredentials = false;
        };

        kernelParams =
          let
            facterReport = config.facter.report;
            memoryBytes = (builtins.head (builtins.head facterReport.hardware.memory).resources).range;
            # ZFS's ARC defaults to using up to ~half of RAM, which starves
            # everything else under memory pressure. A quarter is a safer cap
            # for a laptop that's also running a browser, an editor, etc.
            arcMaxBytes = memoryBytes / 4;
          in
          [
            # Hibernation needs swap large enough to hold all of RAM and
            # surviving a power cycle -- this host only has zram swap
            # (kernel.nix), which is neither, so disable it outright rather
            # than risk a hibernate attempt failing badly. Suspend-to-RAM
            # (see my.idle.suspendTimeout) is unaffected.
            "nohibernate"
            "zfs.zfs_arc_max=${toString arcMaxBytes}"
          ];
      };

      disko.devices.zpool.zroot =
        let
          facterReport = config.facter.report;
          diskInfo = builtins.head facterReport.hardware.disk;
          diskSizeResource = builtins.head (builtins.filter (r: r.type == "size") diskInfo.resources);
          diskSize = builtins.floor (
            (diskSizeResource.value_1 * diskSizeResource.value_2) / (1024 * 1024 * 1024)
          );
        in
        {
          type = "zpool";

          rootFsOptions = {
            acltype = "posixacl";
            canmount = "off";
            checksum = "fletcher4";
            compression = "zstd";
            "com.sun:auto-snapshot" = "false";
            dnodesize = "auto";
            mountpoint = "none";
            normalization = "formD";
            relatime = "on";
            xattr = "sa";
          };

          options = {
            ashift = "12";
            autotrim = "on";
          };

          datasets = {
            reserved = {
              type = "zfs_fs";

              options = {
                canmount = "off";
                mountpoint = "none";
                reservation = "${toString (builtins.ceil (diskSize * 0.05))}G";
              };
            };

            root = {
              mountpoint = "/";
              postCreateHook = "zfs snapshot zroot/root@empty";
              type = "zfs_fs";

              options = {
                "com.sun:auto-snapshot" = "false";
                mountpoint = "legacy";
              };
            };

            nix = {
              mountpoint = "/nix";
              postCreateHook = "zfs snapshot zroot/nix@empty";
              type = "zfs_fs";

              options = {
                atime = "off";
                canmount = "on";
                "com.sun:auto-snapshot" = "false";
                mountpoint = "legacy";
              };
            };

            persist = {
              mountpoint = "/persist";
              postCreateHook = "zfs set com.sun:auto-snapshot=false zroot/persist";
              type = "zfs_fs";

              options = {
                "com.sun:auto-snapshot" = "false";
                mountpoint = "legacy";
              };
            };
          };
        };

      services.zfs.autoScrub.enable = true;

      services.sanoid = {
        enable = true;

        datasets."zroot/persist" = {
          autoprune = true;
          autosnap = true;
          hourly = 24;
          daily = 30;
          # A laptop that's off/asleep for stretches doesn't accumulate
          # snapshots on a reliable cadence -- monthly=3 meant a month away
          # could (and did) collapse coverage to almost nothing. Snapshots
          # are cheap (incremental), so keep deep history instead.
          monthly = 12;
          yearly = 2;
        };
      };
    };
}
